apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
  namespace: airbnb
  labels:
    app: reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
        - name: reservation
          image: 985702435631.dkr.ecr.ap-northeast-2.amazonaws.com/reservation:latest
          ports:
            - containerPort: 8080
#          args:
#            - /bin/sh
#            - -c
#            - touch /tmp/healthy; sleep 90; rm -rf /tmp/healthy; sleep 600
#          readinessProbe:
#            httpGet:
#              path: '/actuator/health'
#              port: 8080
#            initialDelaySeconds: 25
#            timeoutSeconds: 2
#            periodSeconds: 5
#            failureThreshold: 5
#            successThreshold: 1
#          livenessProbe:
#            httpGet:
#              path: '/actuator/health'
#              port: 8080
#            initialDelaySeconds: 120
#            timeoutSeconds: 2
#            periodSeconds: 5
#            failureThreshold: 5
#            successThreshold: 1